name: Build

on: [push, workflow_dispatch]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install libusb

      - name: Compile Gaster
        run: make

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: gaster-macos
          path: gaster
